### ISSUE TITLE
有些手机可以，有些手机说so包缺失

### ISSUE THREAD

**Issue by lmdiloveu** [Marswin/MarsDaemon#26]
Process: cn.mark.frame:process2, PID: 6072
  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.mark.frame-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.mark.frame-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libdaemon_api21.so"

 Process: cn.mark.frame:process1, PID: 6053
 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.mark.frame-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.mark.frame-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libdaemon_api21.so"

**Comment by lmdiloveu** [comment]
请问如何在as中创建出不同cpu架构的so包

**Comment by lmdiloveu** [comment]
Process: cn.mark.frame:process1, PID: 6053
 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.mark.frame-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.mark.frame-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libdaemon_api21.so"
                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                          at java.lang.System.loadLibrary(System.java:988)
                                                                          at com.marswin89.marsdaemon.nativ.NativeDaemonAPI21.<clinit>(NativeDaemonAPI21.java:20)
                                                                          at com.marswin89.marsdaemon.strategy.DaemonStrategy22$1.run(DaemonStrategy22.java:51)

**Comment by chejdj** [comment]
@lmdiloveu 我也遇到这个问题，问一下你是如何解决的?只在自己的手机上跑过

**Comment by emotionfxxk** [comment]
+++ b/libMarsdaemon/jni/Application.mk
@@ -1,2 +1,2 @@
-APP_ABI := armeabi armeabi-v7a x86
-APP_PLATFORM := android-15 
\ No newline at end of file
+APP_ABI := all
+APP_PLATFORM := android-15 

Enable ABI for all.

**Comment by dusx5** [comment]
将so文件放到armeabi，然后在build.gradle设置  
ndk{
   abiFilters 'armeabi'   //设置支持的so库架构
}
然后就可以解决 couldn't find "libdaemon_api21.so" 的问题。
