### ISSUE TITLE
小米4，whetstone.activity: java.lang.NoSuchMethodException: 

### ISSUE THREAD

**Issue by milk1990** [Marswin/MarsDaemon#27]
09-27 16:53:40.281 1719-1745/? E/whetstone.activity: java.lang.NoSuchMethodException: com.android.server.am.ActivityManagerService#clearDeadAppFromNative()#exact
                                                         at miui.util.ReflectionUtils.findMethodExact(ReflectionUtils.java:242)
                                                         at com.miui.whetstone.server.WhetstoneActivityManagerService.handleClearDeadAppFromNative(WhetstoneActivityManagerService.java:246)
                                                         at com.miui.whetstone.server.WhetstoneActivityManagerService.access$400(WhetstoneActivityManagerService.java:51)
                                                         at com.miui.whetstone.server.WhetstoneActivityManagerService$PromoteLevelManagerHandler.handleMessage(WhetstoneActivityManagerService.java:504)
                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                         at android.os.Looper.loop(Looper.java:148)
                                                         at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by milk1990** [comment]
com.miui.whetstone.server.WhetstoneActivityManagerService 是否是由于小米framework修改了ActivityManagerService，所以clearDeadAppFromNative 无法生效，并且报错了，导致无法守护进程？
